---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Course: Tools and Techniques for Data Science</h1>

---
<h3><div align="right">Instructor: Muhammad Arif Butt, Ph.D.</div></h3>    

<h1 align="center">Lecture 3.1 (NumPy-01)</h1>

<a href="https://colab.research.google.com/github/arifpucit/data-science/blob/master/Section-3-Python-for-Data-Scientists/Lec-3.01(NumPy-01-ArrayCreation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# _01-NumPy-ArrayCreation.ipynb_

<img align="center" width="400" height="400"  src="images/numpyintro.png" > 

# Learning agenda of this notebook
1. Introduction to Numpy Library
2. Array Creation using `np.array()` constructor
3. Miscellaneous Array Creation Functions
    - `np.zeros()`
    - `np.ones()`
    - `np.empty()`
    - `np.full()`
    - `np.eye()`
    - `np.fromstring()`
    - `np.arange()`
    - `np.linspace()`
    - `np.random.rand()`
    - `np.random.randint()`
    - `np.zeros_like()`

## 1. Introduction to Numpy Library
<img align="right" width="500" height="300"  src="images/ndarrays.png" > 

- *A **NumPy array** (https://numpy.org) is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.*
- Some attributes of NumPy Array:
>- **ndim:** The number of dimensions, can be 1, 2, 3, ... N
>- **axis:** Each dimension is called an axis: `axis 0` is the vertical axis, goes from top to bottom, represents the number of rows, `axis 1` is the horizontal axis, goes from left to right, represents the number of columns, `axis 2` is the number of columns along z axis
>- **rank:** The number of axes is called the rank.
>- **shape:** It is a tuple whose length is the rank and elements are dimension of each axis.
>- **size:** It is the total number of elements, which is the product of all axis lengths.
>- **itemsize:** It gives you the size in bytes of each element of the array (depends on dtype).
>- **nbytes:** It gives you the total number of bytes occupied by entire array object in memory (size x itemsize).

<img align="left" width="600" height="400"  src="images/numpymemlayout.png" > 
<img align="right" width="300" height="300"  src="images/ndarrayobject.png" > 

To understand the internal memory layout of NumPy ndarray object, consider the four additional attributes:
- A pointer, to block of data in RAM or in a memory-mapped file
- A dtype, that describes fixed-size value cells in the array
- A shape, which is a tuple indicating the array’s shape
- A strides, which is a tuple of integers indicating the number of bytes to “step” in order to advance one element along a dimension (C-Type/Row-Major vs F-Type/Column-Major)
    - Row-Major means that if you have a two-dimensional array of data, the values in each row of the array are stored in adjacent memory locations
    - Column-Major means that if you have a two-dimensional array of data, the values in each column of the array are stored in adjacent memory locations
    
    
    
>- **data:** A pointer to block of data in RAM or in memory-mapped file. (Returns memory address)
>- **dtype:** It gives you the dtype of the numPy array elements (fixed size value cells in memory)
>- **shape:** It gives you a tuple indicating the array's shape
>- **strides:** The strides attribute is a tuple of the same length as the number of axes (dimensions) of the array. The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, in above 2-D array (shown in figure), we have to skip 4 bytes (1 value) to move to the next column, but 12 bytes (3 values) to get to the same position in the next row (for row-major).
    - Row-Major means that if you have a two-dimensional array of data, the values in each row of the array are stored in adjacent memory locations
    - Column-Major means that if you have a two-dimensional array of data, the values in each column of the array are stored in adjacent memory locations
>- **flags:** It gives you information about the memory layout of the array.

In [4]:
import sys
!{sys.executable} -m pip install --upgrade pip

'C:\Users\Awais' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
# Unlike the other modules, we have been working so far, you have to download and install numPy
# To install this library in Jupyter notebook
import sys
!{sys.executable} -m pip install numpy

'C:\Users\Awais' is not recognized as an internal or external command,
operable program or batch file.


In [6]:
import numpy as np
np.__version__ , np.__path__

('1.23.5',
 ['C:\\Users\\Awais Nayyar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy'])

## 2.  Array Creation using `np.array()` Constructor
<img align="right" width="500" height="400"  src="images/numpytypes.png" > 

```
np.array(seq, dtype)
```
- The only required argument is a sequence like object like a list from which to create an array
- The optional `dtype` argument specifies the data type of the array objects. 
- For integer values it is normally int64
- For float values it is normally float64.
- You can mention `dtype` if you want to limit memory usage. 

In [5]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

### a.  Creating an Empty NumPy Array

In [4]:
import numpy as np
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [5]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  []
arr.ndim:  1
arr.shape:  (0,)
arr.size:  0
arr.dtype:  float64
arr.itemsize:  8
arr.nbytes:  0
arr.data:  <memory at 0x000001AE72F6CA00>
arr.strides:  (0,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### b.  0-Dimensional Array
- A 0-D array has a single scalar value, and has zero or no axis

In [6]:
# Create a 0-D numpy array using array() constructor
import numpy as np
arr = np.array(10)
print("array: ", arr)

array:  10


In [5]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (a 0-D array has number of dimensions equals to 0)
print("arr.shape: ", arr.shape) # This is a scalar value, so have no shape ( )
print("arr.size: ", arr.size)   # get total number of elements, in this case it is 1
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the only element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for int64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  10
arr.ndim:  0
arr.shape:  ()
arr.size:  1
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  4
arr.data:  <memory at 0x000001F375065120>
arr.strides:  ()
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### c.  1-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/1d.png" > 

- An array that has 0-D arrays or scalar values, as its elements is called a 1-D array. 
- Used to represent vectors or 1st order tensors.
- A 1-D array has only one axis:
    - **axis 0:** or vertical axis   or x-axis or number of rows

In [9]:
arr = np.array([[5,3,2],[8,9,-1],[2,-3,6]])
arr

array([[ 5,  3,  2],
       [ 8,  9, -1],
       [ 2, -3,  6]])

In [10]:
for i in range(3):
    for j in range(3):
        print(arr[i,j])

5
3
2
8
9
-1
2
-3
6


# 

In [11]:
# Create a 1-D numpy array using array() constructor of numpy

mylist = [1, 4, 2, 5, 3]
arr = np.array(mylist, dtype=np.uint8)
#arr = np.array([1, 4, 2, 5, 3], dtype=np.uint32)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  5
arr.data:  <memory at 0x000001AE792B65C0>
arr.strides:  (1,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



>Note once you print NumPy array elements they are displayed inside `[ ]` as a Python List, however, the elements are space separated in case of NumPy arrays, while in case of Python Lists the elements are comma separated

### d.  2-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/2d.png" > 

- An array that has 1-D arrays as its elements is called a 2-D array. 
- Used to represent matrix or 2nd order tensors.
- A 2-D array has two axis:
    - **axis 0:** is the vertical axis, goes from top to bottom, represents the number of rows (5)
    - **axis 1:** is the horizontal axis, goes from left to right, represents the number of columns (4)
- If you've taken a linear algebra class in high school, you may recognize this 2-d array as a matrix with five rows and four columns. 
- Each row represents a city, and the columns may contain temperature, rainfall, humidity, and smog in that city respectively.

In [17]:
# creating 2-D (5x4) array using array constructor in numpy

mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.dtypes: ", arr.dtype)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]
arr.ndim:  2
arr.shape:  (5, 4)
arr.size:  20
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  80
arr.data:  <memory at 0x000001AE79B017D0>
arr.dtypes:  int32
arr.strides:  (16, 4)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [18]:
arr[1][1]
arr[1:3,:]

array([[5, 6, 7, 8],
       [3, 2, 4, 1]])

In [14]:
# Another example
mylist = [[1], [4], [2], [5], [3]]
arr = np.array(mylist)
arr = np.array([[1], [2], [3]])
print("array: \n", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[1]
 [2]
 [3]]
arr.ndim:  2
arr.shape:  (3, 1)
arr.size:  3
arr.dtype:  int32
arr.itemsize:  4
arr.nbytes:  12
arr.data:  <memory at 0x000001AE79AC4040>
arr.strides:  (4, 4)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### e.  3-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/3d.png" > 

- An array that has 2-D arrays as its elements is called a 3-D array. Used to represent 3rd order tensors.
- A 3-D array has three axis:
    - **axis 0:** represent the number of rows along x-axis(axis 0). (5)
    - **axis 1:** represents the number of rows along y-axis (axis 1). (4)
    - **axis 2:** represents the number of columns along z-axis (axix 2). (3)

In [19]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist, dtype=np.uint8)


print("array: \n", arr)
print("arr.ndim: ", arr.ndim)    # get number of dimensions (3-D array)
print("arr.shape: ", arr.shape)  # get dimension size.For a 3-D array, return a tuple with three elements
print("arr.size: ", arr.size)    # get total number of elements (5*4*3=60 elements)
print("arr.dtype: ", arr.dtype)  # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*60=4800)


print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array: 
 [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]
arr.ndim:  3
arr.shape:  (5, 4, 3)
arr.size:  60
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  60
arr.data:  <memory at 0x000001AE79A936A0>
arr.strides:  (12, 3, 1)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Understanding Strides

In [20]:
# Strides of 1-D array
import numpy as np
mylist = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[3]) # jump 3*8=24 bytes and then read 8 bytes

array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.data:  <memory at 0x000001AE792B6A40>
arr.shape:  (12,)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (8,)
3


In [16]:
# Strides of 2-D array
import numpy as np
mylist = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,2]) # jump 1*32+2*8=48 bytes and then read 8 bytes

array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.data:  <memory at 0x000001F37B670520>
arr.shape:  (3, 4)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 8)
6


In [19]:
arr[2,1]

9

In [21]:
# Strides of 3-D array
import numpy as np
mylist = [
          [[0, 1], [2, 3]],
          [[4, 5], [6, 7]],
          [[8, 9], [10, 11]]
         ]
arr = np.array(mylist, dtype=np.int64)

print("array: \n", arr)
print("arr.data: ", arr.data)
print("arr.shape: ", arr.shape)  
print("arr.dtype: ", arr.dtype)  
print("arr.size: ", arr.size)    
print("arr.itemsize: ", arr.itemsize) 
print("arr.nbytes: ", arr.nbytes)  
print("arr.strides: ", arr.strides)
# Use of strides is in Indexing, slicing and reshaping
print(arr[1,1,1]) # jump 1*32 + 0*16 + 1*8 =40 bytes and then read 8 bytes

array: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
arr.data:  <memory at 0x000001AE79A936A0>
arr.shape:  (3, 2, 2)
arr.dtype:  int64
arr.size:  12
arr.itemsize:  8
arr.nbytes:  96
arr.strides:  (32, 16, 8)
7


## 3. Miscellaneous Array Creation Function
- Numpy also provides some handy methods to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

<img align="right" width="150" height="100"  src="images/zeros.png"  > 

### a. Using `np.zeros()` Method
This method returns an array of given shape and type, filled with zeros.

```
numpy.zeros(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

#####  np.zeros(shape, dtype=float)                     #float 64 in all cases below
##### np.ones(shape, dtype=float)
##### zeros_like(arr, dtype=None)
##### np.empty(shape, dtype=float)                     #fill array with junk values
##### np.full(shape, fill_value, dtype=None)       #makethe array with given fill_values eg. fill_value = 5

##### np.eye(N, M=None, k=0 , dtype=float)       #it always create 2D array
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
  
##### np.fromstring(string, dtype=float, sep='')

##### np.linspace(start, stop, num=50)       #default create 50 numbers start and stop is inclusive
##### np.arange(start, stop, step)                #it will only create 1D array

##### np.random.rand()             #it will return only one random value between 0 and 1 both (exclusive)
##### np.random.rand(2,3)        #it will return a 2D array having 2-rows,3-columns having values bw 0 and 1 both (exclusive)
##### np.random.rand(2,3,3)     #will create a 3D array having 2-level,3-rows,3-columns // // 0 and 1 // (exculive)
##### np.random.rand(5)*10

##### numpy.random.randint(low, high=None, size)  #if not given high number, low is also considered as high number`
                                            #size is the Dimensions size can be (2) or (2,3) or (2,3,2)`



In [8]:
arr = np.arange(10,50, step=1)
arr




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3)
arr
# Notice that the elements are having the default data type as the float. That’s why the zeros are 0.

array([0., 0., 0.])

In [22]:
# Creating 2-Dimensional array filled with zeros
arr = np.zeros((2,3))
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# Creating 2-Dimensional array filled with zeros of integer types
arr = np.zeros((2,3), dtype=np.int16)
arr, arr.nbytes

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 12)

<img align="right" width="100" height="100"  src="images/ones.png"  > 

### b. Using `np.ones()` Method
This method returns an array of given shape and type, filled with ones.

```
numpy.ones(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [22]:
# Creating one-dimensional array with ones
arr = np.ones(3)
arr


array([1., 1., 1.])

In [23]:
# Creating 2-Dimensional array having 3 columns filled with ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Creating 2-Dimensional array having 3 columns filled with ones of integer types
arr = np.ones((2,3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

<img align="right" width="250" height="100"  src="images/empty.png"  > 

### c. Using `np.empty()` Method
This method returns an array of given shape and type, filled with junk values.

```
numpy.empty(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.


Un-like numpy.zeros(), and numpy.ones(), the numpy.empty() function doesn't initialize the entries, so they contain junk values.

In [38]:
arr = np.empty(3)
arr

array([1., 1., 1.])

In [39]:
arr = np.empty(3, dtype=np.int16)
arr

array([257, 257, 257], dtype=int16)

In [40]:
# Creating 2-Dimensional array having 3 columns filled with junk values
arr = np.empty((2,3), dtype=np.int16)
arr

array([[26999, 26987, 25968],
       [26980, 11873, 29295]], dtype=int16)

<img align="right" width="200" height="100"  src="images/full.png"  > 

### d. Using `np.full()` Method
This method return a new array of given shape and type, filled with fill_value.
```
np.full(shape, fill_value, dtype=None)
```
- shape: Shape of the new array
- fill_value: Fill value.
- dtype	The desired data-type for the array

In [41]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [42]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [25]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])

<img align="right" width="120" height="130"  src="images/eye.png"  >

### e. Using `np.eye()` Method
This method is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

```
eye(N, M=None, k=0 , dtype=float)
```
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
- dtype: Data-type of the returned array

In [21]:
# creating 2-D array using eye function
# with 2 rows and 2 columns having 1's at on the main diagonal
eye_arr = np.eye(4,4)
eye_arr
eye_arr.dtype

dtype('float64')

In [52]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at on the main diagonal
eye_arr = np.eye(4, 3, dtype=np.int8)
eye_arr


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)

In [53]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4, 3, k = 1, dtype=int)
eye_arr

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place lower
eye_arr = np.eye(4, 3, k = -1, dtype=int)
eye_arr

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<img align="right" width="200" height="150"  src="images/fromstring.png"  > 

### f. Using `np.fromstring()` Method
This function is used to create a new 1-D array initialized from raw binary or text data in a string.
```
np.fromstring(string, dtype, sep)
```
- string: A string containing the data
- dtype: The data type of the array (by default float)
- sep: The string separating numbers in the data

In [2]:
# convert the space separated string '25 30 35 40' into an floats array
arr = np.fromstring('25 23 35 40',sep = ' ')
arr.dtype

NameError: name 'np' is not defined

In [64]:
# convert the space separated string '25 30 35 40' into an integer array
arr = np.fromstring('25 30 35 40', sep=' ', dtype=np.uint8)
arr

array([25, 30, 35, 40], dtype=uint8)

In [65]:
# converting comma separated string into float type array
arr = np.fromstring('0.7, 10.4, 50.5', sep=",")
print(arr)


[ 0.7 10.4 50.5]


In [25]:
# It will raise error
arr = np.fromstring('23 ,434.4, 242.4, 5.4', sep=',')
print(arr)

[ 23.  434.4 242.4   5.4]


### g. Using `np.arange()` Method
<img align="right" width="200" height="100"  src="images/arrange.png"  > 
This function is used to get evenly spaced values within a given interval.

```
numpy.arange([start,] stop[, step])
```
- If only one argument is given will generate an int64 array from zero to that value (not inclusive)
- If two arguments are given then start value in inclusive, stop value is not inclusive and the default step is 1
- If three arguments are given then the third argument is the distance between two adjacent values. (default step size is 1)
- All the three arguments can be integers or floats

The image shows the array created by np.arange(5,9,1)


In [26]:
import numpy as np
arr = np.arange(5)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
int32


In [2]:
arr = np.arange(5, dtype=float)
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4.]
float64


In [31]:
arr = np.full((3,2), 222)
print(arr.dtype)

int32


In [87]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [4]:
arr = np.arange(5, 10, 2)
arr

array([5, 7, 9])

In [36]:
arr = np.arange(5, 15, -1)
arr

array([], dtype=int32)

In [37]:
arr = np.arange(-1, -4, -.5)
arr

array([-1. , -1.5, -2. , -2.5, -3. , -3.5])

### h. Using `np.linspace()` Method
<img align="right" width="300" height="200"  src="images/linspace1.png"  > 

This method by default returns an array of 50 evenly spaced elements starting from the first argument (inclusive) to the second argument (inclusive). The third argument, if given, is the count of number of elements of the array, default is 50.

```
numpy.linspace(start, stop, num=50)
```

In [38]:
arr = np.linspace(2,3,4)
print(arr)
print(arr.dtype)

[2.         2.33333333 2.66666667 3.        ]
float64


In [8]:
arr = np.linspace(1,2)
print(arr)
print(arr.dtype)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
float64


In [9]:
arr = np.linspace(-1,-5)
print(arr)

[-1.         -1.08163265 -1.16326531 -1.24489796 -1.32653061 -1.40816327
 -1.48979592 -1.57142857 -1.65306122 -1.73469388 -1.81632653 -1.89795918
 -1.97959184 -2.06122449 -2.14285714 -2.2244898  -2.30612245 -2.3877551
 -2.46938776 -2.55102041 -2.63265306 -2.71428571 -2.79591837 -2.87755102
 -2.95918367 -3.04081633 -3.12244898 -3.20408163 -3.28571429 -3.36734694
 -3.44897959 -3.53061224 -3.6122449  -3.69387755 -3.7755102  -3.85714286
 -3.93877551 -4.02040816 -4.10204082 -4.18367347 -4.26530612 -4.34693878
 -4.42857143 -4.51020408 -4.59183673 -4.67346939 -4.75510204 -4.83673469
 -4.91836735 -5.        ]


### i. Using `np.random.rand()` Method
- This method generates an array of random floats (between 0 and 1) of as many dimensions passed as argument.
- If no argument is passed, generates a scalar value between 0 and 1

```
numpy.random.rand(d0 [,d1] [,d2]....)
```


In [91]:
#Python's built-in random module has random() function that returns a single float between 0 and 1
import numpy as np
value = np.random.rand()
value

0.07618578005129628

In [69]:
val = np.random.rand(2,3,3)
val

array([[[0.57281467, 0.01514721, 0.94559597],
        [0.0792593 , 0.46354767, 0.36666667],
        [0.03523472, 0.4238608 , 0.03952085]],

       [[0.74361554, 0.25725968, 0.55074332],
        [0.05769838, 0.90051202, 0.40234631],
        [0.818177  , 0.71369676, 0.03613287]]])

In [10]:
value = np.random.randint(1, 50, (4,4,3))
value


array([[0.3735775 , 0.50770028, 0.17704605],
       [0.64309833, 0.97544964, 0.39985935]])

In [92]:
# Creating 1-D array of 5 elements of random floats between 0 and 1
arr = np.random.rand(5)
arr


array([0.78953939, 0.43154658, 0.63099431, 0.38438024, 0.1481135 ])

In [97]:
# Creating 1-D array of 5 elements of random floats between 0 and 1
arr = np.random.rand(5)*10
arr


array([7.89751696, 4.20533116, 3.8555338 , 2.32378211, 4.5054126 ])

In [122]:
# Creating 2-D array (4x3) having random floats between 0 and 1
arr = np.random.rand(4,3)*10
arr

array([[1.35539004, 1.40514703, 9.75990076],
       [1.16563947, 9.64340946, 1.22029033],
       [3.86789715, 7.14707753, 3.63684563],
       [9.11014009, 4.13384784, 8.28659557]])

In [126]:
# Creating 2-D array (4x3) having random floats between 0 and 10
arr = np.random.rand(4,3)*10
arr

array([[2.12941757, 6.3581262 , 7.33536856],
       [0.32341427, 3.39844643, 4.70210234],
       [0.72218195, 6.56523299, 9.17837935],
       [1.56847094, 9.32525853, 6.10327175]])

In [139]:
# Creating 3-D array of with random values using np.random.rand()
arr = np.random.rand(5,4,3)*10
arr

array([[[4.33870011, 5.71351932, 2.50514132],
        [9.48241864, 6.1789628 , 6.94750581],
        [7.86314589, 3.54654353, 0.98833195],
        [3.42240046, 2.17427766, 5.37727028]],

       [[4.61495415, 3.81460838, 1.52087947],
        [5.45563464, 7.71317078, 2.88365558],
        [7.68376874, 4.60351139, 4.3655072 ],
        [9.3867766 , 7.1149559 , 8.7318746 ]],

       [[1.37346173, 1.59692747, 7.05167173],
        [1.76762688, 9.8417801 , 9.31815599],
        [5.22241605, 5.47621634, 4.99275163],
        [8.92737259, 5.30947065, 2.44528637]],

       [[0.54386998, 2.3711991 , 3.83343661],
        [8.53430257, 4.1440974 , 4.22721861],
        [1.6601333 , 0.54057862, 0.27457621],
        [8.55873838, 7.86061834, 6.72481749]],

       [[4.12766674, 7.46400054, 5.11857989],
        [2.12776123, 8.17466143, 4.09538652],
        [4.58497289, 3.11999728, 6.3247662 ],
        [3.64160174, 1.88452652, 2.40885254]]])

### i. Using `np.random.randint()` Method
This method returns an array of specified shape and fills it with random integers.
```
numpy.random.randint(low, high=None, size)
```
- low: Lowest (signed) integer to be drawn from the distribution. But, it works as a highest integer in the sample if high=None.
- high: Largest (signed) integer to be drawn from the distribution (not inclusive)
- size: number of samples to be generated (default is 1 for scalar and >1 for 1-D array and a tupple for ndarray)

In [146]:
# Generating a random integer scalar b/w interval (0,9) 
value = np.random.randint(10)
value

8

In [167]:
# Generating a random integer scalar b/w interval (5,19) 
value = np.random.randint(low=5, high=20)
value

5

In [174]:
# Generating a random integer scalar from -5 to 4 
value = np.random.randint(low=-5, high=5)
value

-3

In [11]:
# creating 1-D array of size 6 of int type b/w interval (1,100) 
arr = np.random.randint(low=1, high=101, size=(6))
arr

array([40, 96, 45, 36, 75, 51])

In [190]:
# creating 1-D array of size 6 of int type b/w interval (-5,4) 
arr = np.random.randint(low = -5, high = 5, size = 4)
arr

array([-5, -4, -3, -3])

In [195]:
# By passing a tuple to size means rows and columns
arr = np.random.randint(low = 1, high = 10, size = (3,3))
arr

array([[5, 5, 7],
       [3, 5, 4],
       [5, 5, 9]])

In [198]:
arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

array([[[9, 6, 1, 8],
        [7, 4, 7, 1],
        [2, 5, 2, 3]],

       [[5, 2, 9, 1],
        [2, 4, 5, 8],
        [8, 6, 6, 1]]])

<img align="right" width="100" height="130"  src="images/zeros_like.png"  >

### k. Using `np.zeros_like()` Method
This method is used to get an array of zeros with the same shape and type as a given array.

```
zeros_like(arr, dtype=None) 
```

- arr: array like input
- dtype: Overrides the data type of the result

In [202]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)


A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]


In [70]:
# creating 1-D array
arr1 = np.arange(10)
print("A 1-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)
arr2.dtype


A 1-D array 
 [0 1 2 3 4 5 6 7 8 9]

 Converted Array 
 [0 0 0 0 0 0 0 0 0 0]


dtype('int32')

In [204]:
np.fromstring

<function numpy.fromstring>

In [205]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])